name: Rampup
remote_theme: condensat/heliumjk.github.io
title: Condensat technologies
description: Rampup, be a smart bank
site.author.facebook: condensatbank
site.author.twitter: condensat_bank
site.author.linkedin: company/condensat-technologies
